spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mydb
    username: testuser
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 1000

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://idp.example.com/issuer
          jwk-set-uri: https://idp.example.com/.well-known/jwks.json



logging:
  level:
    sql: debug


jwt:
  #HS256 알고리즘을 사용하여 BASE64로 인코딩된 secret key
  secret: eL/qTd8wU/qxrUe/uebKV3/MW+bL86x7DNCz9zRDze0=
