spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mydb
    username: testuser
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 1000

logging:
  level:
    sql: debug

server:
  port: 8080
