spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mydb
    username: testuser
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    sql: debug
